import { useState, useEffect } from 'react'
import { supabase } from '../supabase'

function StaffRegistry() {
  const [staff, setStaff] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({
    full_name: '', staff_type: '', department: '',
    seizure_type: '', medication: '',
    emergency_contact_name: '', emergency_contact_phone: '',
    risk_level: 'Low', status: 'active'
  })

  const staffTypes = ['Teacher','Head of Department','Deputy Rector','Rector','Administrative Staff','Library Staff','Laboratory Technician','Cleaner','Security Officer','Canteen Staff','Other Support Staff']
  const departments = ['Sciences','Mathematics','Languages','Humanities','Physical Education','Arts','ICT','Administration','Support Services','Other']

  useEffect(() => { fetchStaff() }, [])

  async function fetchStaff() {
    setLoading(true)
    const { data } = await supabase
      .from('staff_registry').select('*')
      .eq('status', 'active')
      .order('created_at', { ascending: false })
    setStaff(data || [])
    setLoading(false)
  }

  async function handleSubmit() {
    if (!form.full_name) return alert('Please enter staff name')
    const { error } = await supabase.from('staff_registry').insert([form])
    if (error) return alert('Error: ' + error.message)
    setForm({ full_name: '', staff_type: '', department: '', seizure_type: '', medication: '', emergency_contact_name: '', emergency_contact_phone: '', risk_level: 'Low', status: 'active' })
    setShowForm(false)
    fetchStaff()
  }

  async function deleteStaff(id) {
    if (!confirm('Are you sure?')) return
    await supabase.from('staff_registry').delete().eq('id', id)
    fetchStaff()
  }

  function printStaff(s) {
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>Staff Action Plan - ${s.full_name}</title>
      <style>body{font-family:Arial,sans-serif;padding:40px;color:#333;}h1{color:#1a1a2e;}h2{color:#3ECF8E;margin-top:24px;}.info{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:16px 0;}.info div{padding:8px 12px;background:#f5f5f5;border-radius:6px;}.label{font-size:11px;color:#888;}.value{font-weight:500;}.footer{margin-top:40px;font-size:12px;color:#aaa;border-top:1px solid #eee;padding-top:12px;}</style>
      </head><body>
      <h1>🧠 EpiSafe School — Staff Seizure Action Plan</h1>
      <h2>Staff Details</h2>
      <div class="info">
        <div><div class="label">Full Name</div><div class="value">${s.full_name||'—'}</div></div>
        <div><div class="label">Staff Type</div><div class="value">${s.staff_type||'—'}</div></div>
        <div><div class="label">Department</div><div class="value">${s.department||'—'}</div></div>
        <div><div class="label">Risk Level</div><div class="value">${s.risk_level||'—'}</div></div>
        <div><div class="label">Seizure Type</div><div class="value">${s.seizure_type||'—'}</div></div>
        <div><div class="label">Medication</div><div class="value">${s.medication||'—'}</div></div>
        <div><div class="label">Emergency Contact</div><div class="value">${s.emergency_contact_name||'—'}</div></div>
        <div><div class="label">Emergency Phone</div><div class="value">${s.emergency_contact_phone||'—'}</div></div>
      </div>
      <div class="footer">Generated by EpiSafe School</div>
      </body></html>
    `)
    win.document.close()
    win.print()
  }

  const riskColor = r => r === 'High' ? '#ff4d4f' : r === 'Moderate' ? '#fa8c16' : '#3ECF8E'

  const filteredStaff = staff.filter(s =>
    s.full_name?.toLowerCase().includes(search.toLowerCase()) ||
    s.staff_type?.toLowerCase().includes(search.toLowerCase()) ||
    s.department?.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <div>
          <h1>👨‍🏫 Staff Registry</h1>
          <p>Confirmed epilepsy cases among school staff</p>
        </div>
        <button className="btn btn-primary" onClick={() => setShowForm(!showForm)}>
          {showForm ? 'Cancel' : '➕ Add Staff'}
        </button>
      </div>

      {showForm && (
        <div className="card">
          <h2>New Staff Member</h2>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0 16px' }}>
            <div className="form-group" style={{ gridColumn: '1 / -1' }}>
              <label>Full Name *</label>
              <input value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} placeholder="Full name" />
            </div>
            <div className="form-group">
              <label>Staff Type</label>
              <select value={form.staff_type} onChange={e => setForm({ ...form, staff_type: e.target.value })}>
                <option value="">-- Select --</option>
                {staffTypes.map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label>Department</label>
              <select value={form.department} onChange={e => setForm({ ...form, department: e.target.value })}>
                <option value="">-- Select --</option>
                {departments.map(d => <option key={d} value={d}>{d}</option>)}
              </select>
            </div>
            <div className="form-group">
              <label>Seizure Type</label>
              <select value={form.seizure_type} onChange={e => setForm({ ...form, seizure_type: e.target.value })}>
                <option value="">-- Select --</option>
                <option value="Tonic-clonic (Grand mal)">Tonic-clonic (Grand mal)</option>
                <option value="Absence">Absence</option>
                <option value="Focal (Partial)">Focal (Partial)</option>
                <option value="Atonic (Drop attack)">Atonic (Drop attack)</option>
                <option value="Myoclonic">Myoclonic</option>
                <option value="Unknown / Not yet diagnosed">Unknown / Not yet diagnosed</option>
              </select>
            </div>
            <div className="form-group">
              <label>Medication</label>
              <select value={form.medication} onChange={e => setForm({ ...form, medication: e.target.value })}>
                <option value="">-- Select --</option>
                <option value="Sodium Valproate (Epilim)">Sodium Valproate (Epilim)</option>
                <option value="Carbamazepine (Tegretol)">Carbamazepine (Tegretol)</option>
                <option value="Lamotrigine (Lamictal)">Lamotrigine (Lamictal)</option>
                <option value="Levetiracetam (Keppra)">Levetiracetam (Keppra)</option>
                <option value="Phenobarbitone">Phenobarbitone</option>
                <option value="No medication">No medication</option>
                <option value="Unknown">Unknown</option>
              </select>
            </div>
            <div className="form-group">
              <label>Emergency Contact Name</label>
              <input value={form.emergency_contact_name} onChange={e => setForm({ ...form, emergency_contact_name: e.target.value })} placeholder="Contact name" />
            </div>
            <div className="form-group">
              <label>Emergency Contact Phone</label>
              <input value={form.emergency_contact_phone} onChange={e => setForm({ ...form, emergency_contact_phone: e.target.value })} placeholder="Phone number" />
            </div>
            <div className="form-group">
              <label>Risk Level</label>
              <select value={form.risk_level} onChange={e => setForm({ ...form, risk_level: e.target.value })}>
                <option value="Low">Low</option>
                <option value="Low-Moderate">Low-Moderate</option>
                <option value="Moderate">Moderate</option>
                <option value="High">High</option>
              </select>
            </div>
          </div>
          <button className="btn btn-primary" style={{ marginTop: '8px' }} onClick={handleSubmit}>Save Staff Member</button>
        </div>
      )}

      <div className="card">
        <input value={search} onChange={e => setSearch(e.target.value)} placeholder="🔍 Search by name, type or department..." style={{ marginBottom: '16px' }} />
        {loading ? <p>Loading...</p> : filteredStaff.length === 0 ? (
          <p style={{ textAlign: 'center', padding: '40px', color: '#aaa' }}>
            {search ? 'No staff found.' : 'No staff in registry yet.'}
          </p>
        ) : (
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Staff Type</th>
                <th>Department</th>
                <th>Seizure Type</th>
                <th>Risk</th>
                <th>Emergency Contact</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {filteredStaff.map(s => (
                <tr key={s.id}>
                  <td><strong>{s.full_name}</strong></td>
                  <td>{s.staff_type || '—'}</td>
                  <td>{s.department || '—'}</td>
                  <td>{s.seizure_type || '—'}</td>
                  <td><span style={{ background: riskColor(s.risk_level) + '22', color: riskColor(s.risk_level), border: `1px solid ${riskColor(s.risk_level)}44`, borderRadius: '20px', padding: '2px 10px', fontSize: '12px', fontWeight: '600' }}>{s.risk_level || 'Low'}</span></td>
                  <td>{s.emergency_contact_name}<br /><small style={{ color: '#888' }}>{s.emergency_contact_phone}</small></td>
                  <td style={{ display: 'flex', gap: '6px' }}>
                    <button className="btn btn-secondary" style={{ padding: '4px 10px', fontSize: '12px' }} onClick={() => printStaff(s)}>🖨️</button>
                    <button className="btn btn-danger" style={{ padding: '4px 10px', fontSize: '12px' }} onClick={() => deleteStaff(s.id)}>Remove</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}

export default StaffRegistry