import { useState, useEffect } from 'react'
import { supabase } from '../supabase'

function StaffRegistry() {
  const [staff, setStaff] = useState([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState('')

  useEffect(() => { fetchStaff() }, [])

  async function fetchStaff() {
    setLoading(true)
    const { data } = await supabase.from('staff_registry').select('*').order('created_at', { ascending: false })
    setStaff(data || [])
    setLoading(false)
  }

  async function deleteStaff(id) {
    if (!confirm('Are you sure?')) return
    await supabase.from('staff_registry').delete().eq('id', id)
    fetchStaff()
  }

  function printStaff(s) {
    const win = window.open('', '_blank')
    win.document.write(`
      <html><head><title>Staff Health Profile - ${s.full_name}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        h1 { color: #1a1a2e; } h2 { color: #3ECF8E; margin-top: 24px; }
        .info { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin: 16px 0; }
        .info div { padding: 8px 12px; background: #f5f5f5; border-radius: 6px; }
        .label { font-size: 11px; color: #888; } .value { font-weight: 500; }
        .footer { margin-top: 40px; font-size: 12px; color: #aaa; border-top: 1px solid #eee; padding-top: 12px; }
      </style></head><body>
      <h1>🧠 EpiSafe School — Staff Health Profile</h1>
      <h2>Staff Details</h2>
      <div class="info">
        <div><div class="label">Full Name</div><div class="value">${s.full_name || '—'}</div></div>
        <div><div class="label">Staff Type</div><div class="value">${s.staff_type || '—'}</div></div>
        <div><div class="label">Department</div><div class="value">${s.department || '—'}</div></div>
        <div><div class="label">Has Seizures</div><div class="value">${s.has_seizures || '—'}</div></div>
        <div><div class="label">Seizure Type</div><div class="value">${s.seizure_type || '—'}</div></div>
        <div><div class="label">Medication</div><div class="value">${s.medication || '—'}</div></div>
        <div><div class="label">Vulnerability Level</div><div class="value">${s.risk_level || '—'}</div></div>
        <div><div class="label">Emergency Contact</div><div class="value">${s.emergency_contact_name || '—'}</div></div>
        <div><div class="label">Emergency Phone</div><div class="value">${s.emergency_contact_phone || '—'}</div></div>
        <div><div class="label">Emergency Email</div><div class="value">${s.emergency_contact_email || '—'}</div></div>
      </div>
      <div class="footer">Generated by EpiSafe School — Epilepsy management for Mauritian schools</div>
      </body></html>
    `)
    win.document.close()
    win.print()
  }

  const badgeClass = s => s === 'active' ? 'badge badge-green' : s === 'review' ? 'badge badge-amber' : 'badge badge-red'
  const vulnColors = { High: '#ff4d4f', Moderate: '#fa8c16', 'Low-Moderate': '#fadb14', Low: '#3ECF8E' }
  const vulnScores = { High: 9, Moderate: 6, 'Low-Moderate': 4, Low: 2 }

  const filteredStaff = staff.filter(s =>
    s.full_name?.toLowerCase().includes(search.toLowerCase()) ||
    s.staff_type?.toLowerCase().includes(search.toLowerCase()) ||
    s.department?.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <div>
          <h1>👥 Staff Registry</h1>
          <p>Confirmed staff health profiles</p>
        </div>
      </div>

      <div className="card">
        <input value={search} onChange={e => setSearch(e.target.value)} placeholder="🔍 Search by name, staff type or department..." style={{ marginBottom: '16px' }} />
        {loading ? <p>Loading...</p> : filteredStaff.length === 0 ? (
          <p style={{ textAlign: 'center', padding: '40px', color: '#aaa' }}>
            {search ? 'No staff found matching your search.' : 'No staff in registry yet.'}
          </p>
        ) : (
          <table>
            <thead>
              <tr>
                <th>Name</th><th>Staff Type</th><th>Department</th><th>Vulnerability</th><th>Emergency Contact</th><th>Status</th><th></th>
              </tr>
            </thead>
            <tbody>
              {filteredStaff.map(s => {
                const vulnLevel = s.risk_level && vulnColors[s.risk_level] ? s.risk_level : null
                return (
                  <tr key={s.id}>
                    <td><strong>{s.full_name}</strong></td>
                    <td>{s.staff_type || '—'}</td>
                    <td>{s.department || '—'}</td>
                    <td>
                      {vulnLevel ? (
                        <span style={{ background: vulnColors[vulnLevel] + '22', color: vulnColors[vulnLevel], border: `1px solid ${vulnColors[vulnLevel]}44`, borderRadius: '20px', padding: '2px 10px', fontSize: '0.75rem', fontWeight: '600' }}>
                          {vulnLevel} ({vulnScores[vulnLevel]}/10)
                        </span>
                      ) : '—'}
                    </td>
                    <td>{s.emergency_contact_name || '—'}<br /><small style={{ color: '#888' }}>{s.emergency_contact_phone || '—'}</small></td>
                    <td><span className={badgeClass(s.status)}>{s.status}</span></td>
                    <td style={{ display: 'flex', gap: '6px' }}>
                      <button className="btn btn-secondary" style={{ padding: '4px 10px', fontSize: '0.75rem' }} onClick={() => printStaff(s)}>🖨️ Print</button>
                      <button className="btn btn-danger" style={{ padding: '4px 10px', fontSize: '0.75rem' }} onClick={() => deleteStaff(s.id)}>Remove</button>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}

export default StaffRegistry